project:
  type: website
  output-dir: docs
  resources:
          - "images/equipo/*"

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: quienes_somos.qmd
        text: Quienes somos
      - href: trabajos.qmd
        text: Trabajos realizados 
      - href: proyects.qmd
        text: Proyectos

  sidebar:
    - qmd: sidebar.qmd
      dock: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



